# Generated by Django 4.2.5 on 2023-10-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_image_url_alter_item_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
    ]
